spring.application.name=Project_SWP391_Group4

#spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:sqlserver://;databaseName=swp_project;trustServerCertificate=true;

spring.datasource.username=sa
spring.datasource.password=sa


jwt.secret=levietanhhe181534vianhofico14122004
jwt.expiration=86400000


#send email config
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=he182488toquoctung@gmail.com
spring.mail.pasword=jnzbdpkaywpfwzlf
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


# application.properties
logging.level.org.springframework.security=DEBUG
