spring.application.name=Project_SWP391_Group4

spring.jpa.hibernate.ddl-auto=none
spring.datasource.url=jdbc:sqlserver://;databaseName=swp_project2;trustServerCertificate=true;

spring.datasource.username=sa
spring.datasource.password=1234

spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
#spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=levietanhhe181534vianhofico14122004
jwt.expiration=86400000


#send email config
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=he182488toquoctung@gmail.com
spring.mail.pasword=jnzbdpkaywpfwzlf
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


# application.properties
logging.level.org.springframework.security=DEBUG

# Cloudinary
cloudinary.cloud-name=dhvkumzrj
cloudinary.api-key=267616595125363
cloudinary.api-secret=dlb9agGwdODLHKiYWZtUiKNKtuc
spring.cloud.gcp.credentials.location=classpath:/mr_met_service_account.json
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
# Google OAuth2
spring.security.oauth2.client.registration.google.client-id=none
spring.security.oauth2.client.registration.google.client-secret=none
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo

# Mail
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=vianhofico@gmail.com
#spring.mail.password=nkrcadmxefyqfkxz
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true

spring.kafka.bootstrap-servers=localhost:9092
auto.create.topics.enable=true
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.consumer.group-id=demo-group
spring.kafka.consumer.key-serializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-serializer=org.apache.kafka.common.serialization.StringDeserializer

# Logging
logging.file.name=logs/app.log
logging.level.root=OFF
logging.level.com.javaweb=DEBUG

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.springframework.web=DEBUG
#logging.level.org.springframework.security=DEBUG